#version: '3.8'
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/tz
    depends_on:
      - mysql
      - php
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/tz

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
     - ./src:/var/www/tz
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/tz
    entrypoint: ["php", "/var/www/tz/artisan"]

  mysql:
    image: mysql:8.0
    volumes:
       - database:/var/lib/mysql 
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - env/phpmyadmin.env
    restart: always
    ports:
      - 3135:80
volumes:
  database: